# Generated by Django 2.2 on 2019-07-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeRun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Phone_Number',
            field=models.IntegerField(),
        ),
    ]
